DEFINE VARIABLE FREQUENCY AS INTEGER     NO-UNDO.
DEFINE VARIABLE LINE AS CHARACTER   NO-UNDO.

DEFINE TEMP-TABLE FrequencyTable NO-UNDO
  FIELD FREQUENCY AS INTEGER
  INDEX KEY FREQUENCY.

OuterLoop:
DO WHILE TRUE:
    INPUT FROM day1input.txt.
        REPEAT:
            IMPORT LINE.
            CASE SUBSTRING(LINE,1,1):
                WHEN "+" THEN FREQUENCY = FREQUENCY + INTEGER(TRIM(SUBSTRING(LINE,2))).
                WHEN "-" THEN FREQUENCY = FREQUENCY - INTEGER(TRIM(SUBSTRING(LINE,2))).
            END CASE.
            FIND FrequencyTable WHERE FrequencyTable.FREQUENCY EQ FREQUENCY NO-ERROR.
            IF AVAILABLE FrequencyTable THEN
                LEAVE OuterLoop.
            ELSE DO:
                CREATE FrequencyTable.
                ASSIGN FrequencyTable.FREQUENCY = FREQUENCY.
            END.
        END.
    INPUT CLOSE.
    NEXT OuterLoop.
END.

CLIPBOARD:VALUE = STRING(FREQUENCY).
MESSAGE FREQUENCY
    VIEW-AS ALERT-BOX INFORMATION BUTTONS OK.
