DEFINE VARIABLE FREQUENCY AS INTEGER     NO-UNDO.
DEFINE VARIABLE LINE AS CHARACTER   NO-UNDO.
INPUT FROM day1input.txt.
REPEAT:
 IMPORT LINE.
 CASE SUBSTRING(LINE,1,1):
   WHEN "+" THEN FREQUENCY = FREQUENCY + INTEGER(TRIM(SUBSTRING(LINE,2))).
   WHEN "-" THEN FREQUENCY = FREQUENCY - INTEGER(TRIM(SUBSTRING(LINE,2))).
 END CASE.
 //DISP FREQUENCY.               
END.
INPUT CLOSE.
CLIPBOARD:VALUE = STRING(FREQUENCY).
MESSAGE FREQUENCY
    VIEW-AS ALERT-BOX INFORMATION BUTTONS OK.
